name: Deploy Web ke cPanel via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Mengambil kode terbaru (Checkout)
        uses: actions/checkout@v4

      - name: Sinkronisasi file ke Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: /home/u1zh8984/public_html/assajjad.web.id/
