name: Deploy Web ke cPanel via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Mengambil kode terbaru (Checkout)
        uses: actions/checkout@v4

      - name: Sinkronisasi file ke Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/u1zh8984/public_html/assajjad.web.id/"
